<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Biografía</title>
</head>
<body>
    <h1> Santiago Cardona Prada </h1>
    <p> Naci en Medellin, el 31 de enero de 2004, soy hijo de una Madre Santandereana (Marly Sullay Prada) y un Padre Antioqueño (Fernando Uriel Cardona Rave), tengo 3 hermanos, un hombre, llamado Samuel por parte de mi madre y mi padrastro, y dos niñas, Maria Paula tambien por parte de mi mamá y Emilia Cardona Restrepo.com (Como a ella le gusta ser llamada) por parte de mi papá, ellos son mi razón en esta vida. Las personas no suelen llegar facilmente a mi corazón, pero siento que yo no los escogi a ellos, ellos me escogieron a mi, y haré todo lo posible para que se sientan orgullosos de esa decisión.</p>
    <p2>Mi niñez estuvo muy lejos de ser ideal, soy el unico hijo de un matrimonio que duro apenas 1 año, antes de que se desmoronara por completo, un matrimonio que fue causado por mi nacimiento, cosa de la cual a veces me siento un poco culpable. Tengo claro que no es mi culpa, pero a veces se siente que lo es... Mi recuerdo mas temprano es el de estar siento puesto en una camilla para una curación de mi mano derecha la cual fue quemada por una planca (Era un niño demasiado inquieto jajaja) lo que cual suena bastante peor de lo que realmente era, tenía un año pero ya reconocia que era algo que tenian que hacer por mi si queria poder curarme de mi herida, entonces yo mismo estiraba mi manita en señal de que estaba dispuesto a recibir la curación. No me puedo quejar mucho de mi niñez mas alla del como tuve que crecer sin mi padre debido a que mi mamá le prohibio el verme (Gracias a Dios el batallo para poder volverme a ver) fuera de eso, era lo normal, tenía un techo sobre mi cabeza, a veces tenía hambre, pero nunca al punto de ser una necesidad constante, salia a jugar al escondite y a los diferentes juegos que mis amigos se inventaban en el colegio, ponchado, tapita, tira floja, etc; cabe aclarar que estos nombres no son para nada reales ni oficiales, ya que simplemente los soliamos nombrar por algo que nos recordaba a ello. Lo curioso es que era un pequeño muy, peor muy torpe, me caía con mucha frecuencia y recibi una gran cantidad de cicatrices y huesos rotos, 3 para ser mas exacto, dos veces el codo y una vez el radio... Auch, ahora que lo pienso, es bastante extraño pensar todo lo que había pasado a apenas 8 años de edad. No quiero que me malinterpreten, no fui un niño infeliz, todo lo contrario, me enorgullecia ser el niño mas feliz de todos, el poner una sonrisa y un abrazo calido, aun sabiendo que en casa las cosas no estaban para nada bien, porque eso era lo que quería ser, un niño fuerte, en quien pudieras confiar sin importar que, no era el mas inteligente, mucho menos el mas carismatico, pero si puedo decir que era el mas noble, no iba a dudar nunca en ayudarte si podía hacerlo, en darte mi mano para ayudarte, porque al final del día de eso se trata el ser un heroe. Olvidaba contar eso, mi niñez fue marcada por los super heroes, Spider-Man, Batman, Flash pero el que resaltaba por sobre todos y aun si no era mi favorito (Ese era Spider-Man jeje) sin duda era Super Man, el hombre de acero. Recuerdo ver sus peliculas de los 70 sin parar, no porque fueran mis favoritas, o las mas entretenidas, Dios sabe lo dificil que era ver la 3ra sin querer caerme del sueño, pero para mi era una experiencia magica el ver al hombre de acero, tan inquebrantable como siempre, haciendo todo por la gente del mundo aun si eso significaba no recibir una recompensa. Quería ser como el, quiero ser como el.</p2>
</body>
</html>